### ISSUE TITLE
Flushing does not flush missing rules

### ISSUE THREAD

**Issue by kategee** [Automattic/Rewrite-Rules-Inspector#13]
I've installed the plugin, but hitting the "Flush Rules" button just brings up the same screen that says:

Rewrite rules flushed.

Some rewrite rules may be missing, try flushing.

And all the missing rules re-appear...

**Comment by GaryJones** [comment]
Due to the length of time that this has been open without action on the Automattic side, I'm going to close it out. But if anyone has a similar issue, please open a new ticket with as much detail as possible.
